version: '2'

services:
  web:
    build: .
    volumes:
      - ./:/src
      - /src/node_modules
    ports:
      - '7777:7777'
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - /data/db
