version: '3'

services:
  app:
    build:
      context: /app
      dockerfile: Dockerfile
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
    working_dir: /app

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/db
